name = "cloudflareassignment"
type = "javascript"
account_id = "a30658e358e5a6c636618155808842dc"
workers_dev = true
kv_namespaces = [
  { binding = "MY_KV", id = "fb281f46e2bf48d4812cdf71001bd394" }
]
